openapi: 3.0.0

info:
  title: "Swiss QR Bill API"
  description: |
    The Swiss QR Bill API for generating the new payment slip for invoices. The QR code contains
    the complete payment information in a machine-readable form:

    - Payment amount and currency
    - Creditor address and account
    - Reference number issued by the creditor
    - Additional informationn for the recipient of the invoice
    - Debtor address
    - Alternative payment scheme instructions (future use)

    Debtor and amount can be omitted and filled in by the payer.

    The QR bill can be generated at the bottom of an A4 sheet or on it's own sheet (210 x 105mm). Alternatively,
    only the QR code can be generated. Supported formats are SVG or PDF.

    To successfully validate the bill data and generate a QR bill, the following main requirements must be met:

    - A valid address must at least contain *name*, *postal code*, *town* and *country ISO code*.
    - The creditor address and accout number are mandatory.
    - The debtor addresses is optional. If is not used, it must be omitted entirely
      or all address fields must be *null* or empty.
    - The account number must be a valid IBAN of Switzerland or Liechtenstein.
    - If a reference number is provided, it must be either a valid QR/ISR reference number
      or a valid ISO 11649 creditor reference (i.e. the applicable check digits must be valid)
    - The currency must be either *CHF* or *EUR*.

    If fields are too long, they are automaticalluy truncated. If characters outside the restricted range of
    characters are used, they are automatically replaced. The validation result contains warnings about
    truncations and replacements.

  version: 2.0.0-RC3
  license:
    name: "MIT License"
    url: "https://opensource.org/licenses/MIT"

servers:
- url: "https://www.codecrete.net/qrbill-api"

tags:
- name: bills
  description: "Generate and validate QR bills"

paths:
  /bill/validated:
    post:
      tags:
      - bills
      summary: "Validate the data for a QR bill"
      description: "Validates the data for a QR bill. The result contains a list of errors (if any), a bill ID (if the data is valid) and the possibly modified bill data."
      operationId: validateBill
      requestBody:
        required: true
        description: "Bill data to be validated"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/QrBill"
      responses:
        '200':
          description: "Validation result"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationResponse"

  /bill/image:
    post:
      tags:
      - bills
      summary: "Generates QR bill as SVG or PDF"
      operationId: "generateBill"
      requestBody:
        required: true
        description: "Bill data"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/QrBill"
      responses:
        '200':
          description: "QR bill as SVG or PDF"
          content:
            image/svg+xml:
              schema:
                type: string
                format: binary
            application/pdf:
              schema:
                type: string
                format: binary
        '422':
          description: "Validation error"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ValidationMessage"

  /bill/image/{billID}:
    get:
      tags:
      - bills
      summary: "Generates QR bill as SVG or PDF"
      operationId: getBillImage
      parameters:
      - in: path
        name: billID
        description: "Bill ID as returned by the validation response. Specifies the QR bill data and formatting."
        required: true
        schema:
          type: string
      - in: query
        name: outputSize
        description: "Overrides the output size of the generated QR bill (or QR code)"
        required: false
        schema:
          type: string
          enum:
          - "a4-portrait-sheet"
          - "qr-bill-only"
          - "qr-code-only"
      - in: query
        name: graphicsFormat
        description: "Overrides the graphics format of the generated QR bill (or QR code)"
        required: false
        schema:
          type: string
          enum:
          - "svg"
          - "pdf"
      responses:
        '200':
          description: "QR bill as SVG or PDF"
          content:
            image/svg+xml:
              schema:
                type: string
                format: binary
            application/pdf:
              schema:
                type: string
                format: binary
        '422':
          description: "Validation error"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ValidationMessage"

  /bill/qrdata:
    post:
      tags:
      - bills
      summary: "Decode the text embedded in the QR code and return it as bill data"
      operationId: decodeQRCode
      requestBody:
        description: "QR code information"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/QrCodeInformation"
      responses:
        '200':
          description: "Validation result (incl. bill data)"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationResponse"

components:
  schemas:

    Address:
      type: object
      description: |
        Address of creditor or debtor. Unless the entire object is empty, *name*, *postal code*, *town* and
        *country code* are mandatory. Some fields are mutually exclusive: either *street*, *houseNo*, *town* and
        *postalCode* are used (so called structured addresses) or *addressLine1* and *addressLine2* are used
        (so called combined elements addresses).
      properties:
        addressType:
          type: string
          description: "Address type"
          enum:
          - "undetermined"
          - "structured"
          - "combined-elements"
          - "conflicting"
        name:
          type: string
          description: "First, middle and last name of a natural person or company or organization name of a legal person"
        addressLine1:
          type: string
          description: "First address line containing street name, house number and P.O. box"
        addressLine2:
          type: string
          description: "Second address line containing postal code and town"
        street:
          type: string
          description: "Street name (without the house number)"
        houseNo:
          type: string
          description: "House or building number"
        town:
          type: string
          description: "Town or city name"
        postalCode:
          type: string
          description: "Postal code"
        countryCode:
          type: string
          description: "Two letter ISO country code"

    BillFormat:
      type: object
      description: |
        Formatting information for QR bill
      properties:
        language:
          type: string
          description: "Language of the generated QR bill"
          enum:
          - "de"
          - "fr"
          - "it"
          - "en"
        graphicsFormat:
          type: string
          description: "Graphics format of generated QR bill"
          enum:
          - "svg"
          - "pdf"
        outputSize:
          type: string
          description: "Output size of generated QR bill"
          enum:
          - "a4-portrait-sheet"
          - "qr-bill-only"
          - "qr-code-only"
        separatorType:
          type: string
          description: "Type of separator lines above and between payment part and receipt"
          enum:
          - "none"
          - "solid-line"
          - "solid-line-with-scissors"
        fontFamily:
          type: string
          description: "Font family used for text"

    QrBill:
      type: object
      description: |
        QR bill data
      properties:
        version:
          type: string
          description: "QR bill specification version"
          default: "V2_0"
        amount:
          type: number
          description: "Bill amount"
        currency:
          type: string
          default: "CHF"
          description: "Bill currency"
        account:
          type: string
          description: "Creditor's account"
        creditor:
          $ref: "#/components/schemas/Address"
        reference:
          type: string
          description: "Payment reference number (QR/ISR reference number or ISO 11649 creditor reference)"
        unstructuredMessage:
          type: string
          description: "Message for the bill recipient"
        billInformation:
          type: string
          description: "Structured bill information for recipient"
        debtor:
          $ref: "#/components/schemas/Address"
        alternativeSchemes:
          type: array
          items:
            $ref: "#/components/schemas/AlternativeScheme"
        format:
          $ref: "#/components/schemas/BillFormat"

    ValidationMessage:
      type: object
      description: |
        Message generated as the result of bill data validation
      properties:
        type:
          type: string
          description: "Message type (error or warning)"
          enum:
          - "Error"
          - "Warning"
        messageKey:
          type: string
          description: "Language independent message key"
        messageParameters:
          type: array
          description: "Variable parts of the message (if any)"
          items:
            type: string
        message:
          type: string
          description: "Localized message (incl. variable parts). The Accept-Language header field is used to select a suitable language."
        field:
          type: string
          description: "Affected field name. Examples are Examples are: \"account\", \"creditor.street\""

    ValidationResponse:
      type: object
      description: |
        Result of bill data validation
      properties:
        valid:
          type: boolean
          description: "Indicates if the bill data was valid or not"
        validationMessages:
          type: array
          items:
            $ref: "#/components/schemas/ValidationMessage"
        validatedBill:
          $ref: "#/components/schemas/QrBill"
        billID:
          type: string
          description: "Bill ID if the bill data was valid. Used to retrieve the QR bill as SVG or PDF."
        qrCodeText:
          type: string
          description: "Text embedded in QR code if the bill data was valid."

    QrCodeInformation:
      type: object
      description: |
        Text embedded in QR code of a QR bill
      properties:
        text:
          type: string
          description: "QR code text"

    AlternativeScheme:
      type: object
      description: |
        Alternative processing information / payment scheme
      properties:
        name:
          type: string
          description: "Scheme name"
        instruction:
          type: string
          description: "Payment instruction"

externalDocs:
  description: "Find out more about Swiss QR Bill"
  url: "https://github.com/manuelbl/SwissQRBill"
